### ISSUE TITLE
Unix Socket Connects Fail For Postgres

### ISSUE THREAD

**Issue by daaasbu** [prisma/prisma-client-js#437]
Following up from issue: [525](https://github.com/prisma/prisma2/issues/525)

 I'm using a typical docker compose for postgres to repro locally, that listens on unix socket: /var/run/postgresql/.s.PGSQL.5432. 

```
version: "3.7"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432`
```
I am on alpha version: **2.0.0-alpha.538**.  I believe this is the last alpha version before the breaking changes introduced that migrate off of photon. I would upgrade but I also use nexus-prisma, so I'm waiting on the changes coming in there. 

Nexus version:     "nexus-prisma": "0.6.1",

I'm in a similar situation where I would like to use this with Google Cloud Run and Cloud SQL in GCP. 

When I try to make a gql query I get this error: 

```
Invalid `photon.()` invocation in
/home/dana/Projects/flags/flag-core/flag-api/node_modules/nexus-prisma/src/builder.ts:238:18

Error parsing connection string: empty host
    at PhotonFetcher.request (/home/dana/Projects/flags/flag-core/flag-api/node_modules/@prisma/photon/index.js:62:23)
```

With the connection string (replace dbname)

```
POSTGRESQL_URL=postgresql://postgres:mypassword@/<dbname>?host=/var/run/postgresql/
```

I am able to connect to this just fine using other connection methods with a connection string.
