### ISSUE TITLE
Bug with generators

### ISSUE THREAD

**Issue by robertwestbury** [prisma/prisma-client-js#620]
So I really want to use Prisma but I've had a lot of troubles setting it up (monorepos, tooling and app sharing the same url, etc), but now I have a problem I am really unable to solve.

My docker-compose looks like this:
```yml
version: '3'

services:
  app:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    links:
      - postgres
    command: npm run nx serve api

  postgres:
    image: postgres
    restart: 'always'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: '...'
      POSTGRES_DB: '...'
      POSTGRES_PASSWORD: '...'
      PGPORT: 5432
```
And my Prisma file looks like this:
```
datasource db {
  provider = "postgresql"
  url      = "..."
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

model User {
  id       String @default(uuid()) @id
  username String @unique
  email    String @unique
  password String
}
```
The problem is, whenever I run PrismaClient#connect I get this error:
```
app_1       | (node:90) UnhandledPromiseRejectionWarning: Error: Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
app_1       | This probably happens, because you built Prisma Client on a different platform.
app_1       | (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x")
app_1       | 
app_1       | You already added the platform "native" to the "generator" block
app_1       | in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
app_1       | but something went wrong. That's suboptimal.
app_1       | 
app_1       | Please create an issue at https://github.com/prisma/prisma-client-js/issues/new
```
I've been trying to figure this out for a while and this is a really discouraging sign as a person trying to get into Prisma.
